### PR TITLE
Increase severity of consistent-this, eqeqeq, prefer-const rules

### LINKED ISSUE #49: Increase prefer-const to an error
This should be increased to an error in a future revision, after folks have had the chance to correct the warning.

For the PR that enabled this behavior, see https://github.com/segmentio/eslint-config/pull/47

### PR DESCRIPTION
**Pull request by ndhoule**
Closes #49

### CODE REVIEW

**Comment by ndhoule** [comment]
On the heels of @stephenmathieson reminding me that warnings are just BS noise, I'm gonna start disabling warning rules we ignore and elevating real things like this to errors. (Please do the same)

cc @stephenmathieson @dominicbarnes, speak now or hold your peace etc.

**Comment by stephenmathieson** [comment]
im considering breaking away from this repo in "app", since i disagree with tons of decisions made here (for example, stylistic things causing builds to break) and @stevenmiller888 and i are the two maintaining it (not either @ndhoule or @dominicbarnes)...

also, this will cause app builds to fail, since we do this in a few spots:

``` js
const ctx = this
const something = yield getSomething(ctx, this.state.user, whatever)
```

**Comment by stephenmathieson** [comment]
the prefer const thing will also break app, but im in favor of that one, since it does actually cause real problems

**Comment by dominicbarnes** [comment]
@stephenmathieson are you saying you'll stop using this config module? Couldn't you just override any disagreements you have in the local `.eslintrc`? (or is that what you're saying)

**Comment by stephenmathieson** [comment]
yeah, could override everything too.. or i could start over and just do what everyone else does and adopt "standard" or something

also, i just don't think any of these things should break a build:

``` js
function(){}
if (x == y) doSomething()
const array = [ 1, 2, 3, 4, ];
const array = [ 1, 2, 3, 4 ]
function*(){}
```

...or the countless other super trivial style things people argue about.

imo, this repo and debates about semicolons are wastes of valuable time that could be spent fixing bugs and/or adding features to our products

**Pull request merged**
